//Povray v3 code generated by Open Babel
//Author: Steffen Reith <streit@streit.cc>
//Update (2010): Noel O'Boyle and Steven Wathen
//Date: Tue Dec 09 11:33:29 CET 2025

//Set some global parameters for display options
#declare BAS = true;
#declare TRANS = false;

#include "colors.inc"

// create a regular point light source
light_source {
  <3.74702,2.68359,-8.14422>
  color rgb <1,1,1>    // light's color
}

// set a color of the background (sky)
background { color rgb <0.95 0.95 0.95> }

// perspective (default) camera
camera {
  location  <1.74702,-0.316413,-10.1442>
  look_at   <1.74702,-0.316413,-0.144223>
  right     x*image_width/image_height
}

//Include header for povray
#include "babel_povray3.inc"

//Use PovRay3.6
#version 3.6;

//Print name of molecule while rendering
#render "\b\b \n\n"

//Coodinates of atoms 1 - 8
#declare mol_0_pos_1 = <0.990259,-0.114583,-0.0292107>;
#declare mol_0_pos_2 = <2.48695,-0.0503051,0.00741813>;
#declare mol_0_pos_3 = <3.12504,0.853299,0.522337>;
#declare mol_0_pos_4 = <3.072,-1.10872,-0.595721>;
#declare mol_0_pos_5 = <0.578608,0.765923,0.472543>;
#declare mol_0_pos_6 = <0.643637,-1.00767,0.496569>;
#declare mol_0_pos_7 = <0.643637,-0.117491,-1.06557>;
#declare mol_0_pos_8 = <2.43607,-1.75175,-0.962148>;

//Povray-description of atoms 1 - 8
#declare mol_0_atom1 = object {
	  Atom_C
	  translate mol_0_pos_1
	 }
#declare mol_0_atom2 = object {
	  Atom_C
	  translate mol_0_pos_2
	 }
#declare mol_0_atom3 = object {
	  Atom_O
	  translate mol_0_pos_3
	 }
#declare mol_0_atom4 = object {
	  Atom_O
	  translate mol_0_pos_4
	 }
#declare mol_0_atom5 = object {
	  Atom_H
	  translate mol_0_pos_5
	 }
#declare mol_0_atom6 = object {
	  Atom_H
	  translate mol_0_pos_6
	 }
#declare mol_0_atom7 = object {
	  Atom_H
	  translate mol_0_pos_7
	 }
#declare mol_0_atom8 = object {
	  Atom_H
	  translate mol_0_pos_8
	 }

//Povray-description of bonds 1 - 7
#if (BAS)
#declare mol_0_bond0 = object {
	  bond_1
	  scale <1.49852,1.0000,1.0000>
	  rotate <0.0000,0.0000,2.45842>
	  rotate <0.0000,-1.40193,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond1 = object {
	  bond_2
	  scale <1.22016,1.0000,1.0000>
	  rotate <0.0000,0.0000,47.7793>
	  rotate <0.0000,-38.9029,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond2 = object {
	  bond_1
	  scale <1.35141,1.0000,1.0000>
	  rotate <0.0000,0.0000,-51.5541>
	  rotate <0.0000,45.8722,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond3 = object {
	  bond_1
	  scale <1.09385,1.0000,1.0000>
	  rotate <0.0000,0.0000,53.6066>
	  rotate <0.0000,-129.366,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond4 = object {
	  bond_1
	  scale <1.09279,1.0000,1.0000>
	  rotate <0.0000,0.0000,-54.8107>
	  rotate <0.0000,-123.395,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond5 = object {
	  bond_1
	  scale <1.09279,1.0000,1.0000>
	  rotate <0.0000,0.0000,-0.152457>
	  rotate <0.0000,108.493,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond6 = object {
	  bond_1
	  scale <0.975791,1.0000,1.0000>
	  rotate <0.0000,0.0000,-41.2219>
	  rotate <0.0000,150.05,0.0000>
	  translate mol_0_pos_4
	 }
#end //(BAS-Bonds)

#if (CST)
#declare mol_0_bond0 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.749261,1.0000,1.0000>
	    rotate <0.0000,0.0000,2.45842>
	    rotate <0.0000,-1.40193,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.749261,1.0000,1.0000>
	    rotate <0.0000,0.0000,182.458>
	    rotate <0.0000,-1.40193,0.0000>
	    translate mol_0_pos_2
	   }
	  }
	 }

#declare mol_0_bond1 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_C2}
	    scale <0.61008,1.0000,1.0000>
	    rotate <0.0000,0.0000,47.7793>
	    rotate <0.0000,-38.9029,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_2
	    pigment{color Color_O2}
	    scale <0.61008,1.0000,1.0000>
	    rotate <0.0000,0.0000,227.779>
	    rotate <0.0000,-38.9029,0.0000>
	    translate mol_0_pos_3
	   }
	  }
	 }

#declare mol_0_bond2 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.675706,1.0000,1.0000>
	    rotate <0.0000,0.0000,-51.5541>
	    rotate <0.0000,45.8722,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.675706,1.0000,1.0000>
	    rotate <0.0000,0.0000,128.446>
	    rotate <0.0000,45.8722,0.0000>
	    translate mol_0_pos_4
	   }
	  }
	 }

#declare mol_0_bond3 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.546924,1.0000,1.0000>
	    rotate <0.0000,0.0000,53.6066>
	    rotate <0.0000,-129.366,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.546924,1.0000,1.0000>
	    rotate <0.0000,0.0000,233.607>
	    rotate <0.0000,-129.366,0.0000>
	    translate mol_0_pos_5
	   }
	  }
	 }

#declare mol_0_bond4 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.546396,1.0000,1.0000>
	    rotate <0.0000,0.0000,-54.8107>
	    rotate <0.0000,-123.395,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.546396,1.0000,1.0000>
	    rotate <0.0000,0.0000,125.189>
	    rotate <0.0000,-123.395,0.0000>
	    translate mol_0_pos_6
	   }
	  }
	 }

#declare mol_0_bond5 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.546396,1.0000,1.0000>
	    rotate <0.0000,0.0000,-0.152457>
	    rotate <0.0000,108.493,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.546396,1.0000,1.0000>
	    rotate <0.0000,0.0000,179.848>
	    rotate <0.0000,108.493,0.0000>
	    translate mol_0_pos_7
	   }
	  }
	 }

#declare mol_0_bond6 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.487895,1.0000,1.0000>
	    rotate <0.0000,0.0000,-41.2219>
	    rotate <0.0000,150.05,0.0000>
	    translate mol_0_pos_4
	   }
	   object {
	    bond_1
	    pigment{color Color_HO}
	    scale <0.487895,1.0000,1.0000>
	    rotate <0.0000,0.0000,138.778>
	    rotate <0.0000,150.05,0.0000>
	    translate mol_0_pos_8
	   }
	  }
	 }

#end // (CST-Bonds)


//All atoms of molecule mol_0
#ifdef (TRANS)
#declare mol_0_atoms = merge {
#else
#declare mol_0_atoms = union {
#end //(End of TRANS)
	  object{mol_0_atom1}
	  object{mol_0_atom2}
	  object{mol_0_atom3}
	  object{mol_0_atom4}
	  object{mol_0_atom5}
	  object{mol_0_atom6}
	  object{mol_0_atom7}
	  object{mol_0_atom8}
	 }

//Bonds only needed for ball and sticks or capped sticks models
#if (BAS | CST)
#declare mol_0_bonds = union {
	  object{mol_0_bond0}
	  object{mol_0_bond1}
	  object{mol_0_bond2}
	  object{mol_0_bond3}
	  object{mol_0_bond4}
	  object{mol_0_bond5}
	  object{mol_0_bond6}
	 }
#end


//Definition of molecule mol_0
#if (SPF)
#declare mol_0 = object{
	  mol_0_atoms
#else
#declare mol_0 = union {
	  object{mol_0_atoms}
#if (BAS | CST)//(Not really needed at moment!)
#if (TRANS)
	  difference {
	   object{mol_0_bonds}
	   object{mol_0_atoms}
	  }
#else
	  object{mol_0_bonds}
#end //(End of TRANS)
#end //(End of (BAS|CST))
#end //(End of SPF)
//	  bounded_by {
//	   box {
//	    <-3,-4.75175,-4.06557>
//	    <6.12504,3.8533,3.52234>
	 }

//Center of molecule mol_0 (bounding box)
#declare mol_0_center = <-1.56252,0.449225,0.271616>;
